### ISSUE TITLE
Newrelic Integration - Technical Error while creating DataExchangeAPI Client:NL-API-ERROR

### ISSUE THREAD

**Issue by nithinkvGitHub** [Neotys-Labs/NewRelic#10]
Executing advanced action New Relic (first execution).
Parameters: newRelicAPIKey: XXX, newRelicApplicationName: XXXXX, sendNLWebDataToNewRelic: true, newRelicLicenseKey: XXX, newRelicAccountId: XXXXX, newRelicInsightsAPIKey: XXX, dataExchangeApiUrl: null, dataExchangeApiKey: XXX, proxyName: null, newRelicRelevantMetricNames: null, newRelicRelevantMetricValues: null, tls.insecure: null
NewRelicRestClient created.

<?xml version="1.0" encoding="UTF-8"?><Output>
    <Status state="ERROR">Technical Error while creating DataExchangeAPI Client:NL-API-ERROR</Status>
</Output>

Given Ingest licence key for "newRelicLicenseKey" and "newRelicInsightsAPIKey" and user key for "newRelicAPIKey"

**Comment by guillaumebert** [comment]
It could be due to the `dataExchangeApiUrl: null` parameter.
Make sure you set the correct API Key taken from either:
* NeoLoad > Edit > Preferences > General > REST API > Identification
* NeoLoad > Edit > Preferences > Project settings > REST API > Identification

If the problem persist, please open a support case [from NeoLoad suport](https://www.neotys.com/redirect/redirect.php?target=support&product=neoload+web&lngdoc=en) providing the NeoLoad Logs.
